### ISSUE TITLE
OJSolver Outputs Incorrect Solution For Minimization Problem

### ISSUE THREAD

**Issue by gm2211** [vagmcs/Optimus#25]
Update: This is likely related to the fact that `objectiveValue = -(x * y)`, with `x` and `y` both being unknowns, is not a linear nor a quadratic equation. However, if that's in fact the reason, wouldn't there be a way of detecting when the entered equation cannot be minimized because not linear nor quadratic rather than outputting an incorrect solution?

--------------
I might be missing something here, but the following:

![image](https://user-images.githubusercontent.com/1555460/44993463-ac7af900-af68-11e8-8012-3f64dd5b3dbe.png)

outputs:

![image](https://user-images.githubusercontent.com/1555460/44993475-b8ff5180-af68-11e8-8322-e7aae135d387.png)

while I would expect `x = 200`, `y = 170` and `objectiveValue = -34,000`.

It says the solution state is `OPTIMAL` but, unless I'm missing something, this is incorrect.

**Comment by apete** [comment]
If you think you've found a problem with ojAlgo it's better you create an issue with that project: https://github.com/optimatika/ojAlgo

The model is not convex. That's why ojAlgo can't handle it properly. Returning a solution and reporting it to be optimal is not correct behaviour, but I'm little unsure what to do about it. It's possible to turn on validation in ojAlgo. If you do that ojAlgo throws an IllegalArgumentException and outputs:
```
Q not positive semidefinite!
The eigenvalues are: [(0.9999999999999998 + 0.0i), (-1.0 + 0.0i)]
```
That kind of validation is expensive and turned off by default.

**Comment by gm2211** [comment]
I see two options here (not necessarily mutually exclusive):

1. Adding an entry to the README, explicitly calling this out with an example (e.g. "NOTE: an expression of the form `x * y`, with `x` and `y` both being variables of the model, does not represent a convex model and some of the solvers will return an incorrect solution unless model validation is enabled. Model validation is expensive and turned off by default."). Or at least mention that validation is off by default and because of that the model might return incorrect results for invalid models instead of throwing an exception and that if one wants absolute correctness, they need to turn on model validation.

2. I'd propose to turn on expensive validation by default, with a warning log like: "If you are experiencing poor performance and you are sure your models are valid, you can turn off model validation to experience a performance gain.". I believe that correctness is more important than performance. It can be easy, especially if one's models are generated, instead of manually defined, to end up with an invalid model and take an incorrect solution as optimal. 

That being said, I'll also file an issue with ojAlgo when I get a chance, but I'm not sure there's much to be done except doing model validation.

**Comment by apete** [comment]
This is now fixed in ojAlgo's development branch. (v47 and onwards will have this fix.)

The initial/candidate solution supplied by the model to the solver has been "improved" and then the convex solver makes better use of it. The combination of those two improvements means this problem, and hopefully a few more, can now be solved correctly.

ojAlgo will not turn on validation by default. That feature is meant to be turned on to help debug when something does not work as expected. Apart from being expensive to always have turned on it will fail some cases that in practice can be solved. (Like this one.)

**Comment by vagmcs** [comment]
Thank you @apete. I will update to ojAlgo v47.
