### ISSUE TITLE
Trigger log output

### ISSUE THREAD

**Issue by yangguang760** [vagmcs/Optimus#27]
When running the program many times, the output of the logo and time may be verbose. How can I close this log output?
Thank you.

**Comment by vagmcs** [comment]
Hi @yangguang760,

You should close the logger of Optimus on the logback xml file inside your project. For instance, if your appender is called STDOUT, you can add the following lines:

```xml
<logger name="optimus" level="off">
        <appender-ref ref="STDOUT"/>
</logger>
```

**Comment by yangguang760** [comment]
@vagmcs 
Thanks for your answer.
Certainly, your solution would work well.
When running unit tests or JMH, usually there is no configuration for logback. 
On the other hand, in my opinion, the time measurement information may be classified into DEBUG.

**Comment by vagmcs** [comment]
@yangguang760  
That's correct, but during unit testing or JMH it is also good to have a somehow more verbose output in order to see if everything works correctly. However, if you prefer to use Optimus with a specific configuration for the logger and you do not want to add a logback xml file to your project, you can also clone Optimus, change the logback.xml file inside Optimus and then just run `sbt publishLocal` as described in section [Local publish Optimus](https://github.com/vagmcs/Optimus/blob/master/docs/building_and_linking.md#local-publish-optimus).
