### ISSUE TITLE
Improve Gurobi support

### ISSUE THREAD

**Issue by danoliv** [vagmcs/Optimus#42]
The library is not working with recent versions of Gurobi. 
The update is trivial (I've already did it) but I find a little cumbersome to have to manually copy the jar when in fact gurobi provides the library on maven central.

https://central.sonatype.com/artifact/com.gurobi/gurobi/12.0.0

I propose the following changes to improve Gurobi support (in order of priority): 
- fix the code to be compatible with recent versions 
- allow to provide license details in the interface
- get java library from maven

Another small question, how do you build it and release it ? do you have an academic or open source license for it ?

Please can I have your feedback on this ? I can open a MR quite soon.

**Comment by vagmcs** [comment]
Hi @danoliv,

Indeed, there has been some time since I update Gurobi. I used to have an academic license. Anyway, I issued a license for non-commercial usage which support up to 2000 variables, which is fine for testing.  I updated the code to run with the newer version and added the Maven dependency in order to avoid copying the jar file. I have pushed everything into the develop branch. Can you have a look and confirm that it works as expected?

**Comment by apete** [comment]
Maybe it's time to update all the solvers. ojAlgo has been much improved the last couple of years. The latest version is v55.0.0

**Comment by vagmcs** [comment]
Hi @apete,

I pushed an update yesterday to the develop branch for ojalgo version 53.3.0. However, after upgrading to the newest version (55.0.0), I am encountering test errors. I haven't identified the root cause yet, but I'll be investigating further. If you're aware of any significant changes in version 55.0.0 that could potentially impact test results, I would appreciate any insights or advice you might have.

**Comment by apete** [comment]
Not my intention to highjack the thread. Maybe we should have another one for this.

There are significant internal changes, so altered behaviour in some cases must be expected. That said, there are no known issues. In general the newer version performs better, and succeeds in more cases.

I'm not a Scala developer, but if you can point to what test cases fail I'll have look at it (try to reproduce it).

**Comment by vagmcs** [comment]
@apete, I created another issue [here](https://github.com/vagmcs/Optimus/issues/43). I have added a short description of the problem and the test case failing.

**Comment by danoliv** [comment]
Thanks @vagmcs, I've verified the updates, the changes are pretty straightforward.
