### ISSUE TITLE
Update ojAlgo to the latest version

### ISSUE THREAD

**Issue by vagmcs** [vagmcs/Optimus#43]
The [Linear Program 3](https://github.com/vagmcs/Optimus/blob/3b2d1cd00f290e5830bee3f2a3808a16ed46a820/solver-oj/src/test/scala/optimus/optimization/OJAlgorithmsSpecTest.scala#L180) test case is failing. I am getting a `java.lang.NumberFormatException, construction cannot continue: Infinite or NaN` from the underlying `ExpressionBasedModel` in the [optimize method](https://github.com/optimatika/ojAlgo/blob/aa42bc8388d92b4653778df85f96a2843fe7fae0/src/main/java/org/ojalgo/optimisation/ExpressionsBasedModel.java#L1592). It seems to be something related to BigDecimal.

**Comment by apete** [comment]
I see the issue. Hopefully easy to fix, but until it's actually done and working...

The problem is unbounded (not infeasible). A feasible solution is x=120 and y=80.

In this case ojAlgo finds a feasible solution, but then somehow fails to identify that it's unbounded and instead returns a solution with an infinite value.

**Comment by apete** [comment]
That was easy to fix. Will release v55.0.1 later this weekend, and let you know here when it's available.

**Comment by apete** [comment]
https://repo1.maven.org/maven2/org/ojalgo/ojalgo/55.0.1/

May take a while before it's visible everywhere.

**Comment by vagmcs** [comment]
Thank you @apete. I have updated the develop branch to ojalgo 55.0.1. Tests work as expected. I will publish a new version of Optimus soon.
